### ISSUE TITLE
Customize script to handle multiple command line arguments

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#1]
Customize script to handle multiple command line arguments. Currently it can accept only "oie".

Hi @jeevanjagadeesh , can you take care of this?

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , Fixed

Please run as mentioned below 
node dq_cli.js -src oie > logs/dq.log &

Note - make sure to create logs folder in your local dirctory

**Comment by rajeshgrs** [comment]
Thanks much Jeevan. Let me check it out.

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , is this functionality sufficient ? 
Or do you need to take an array for the same key ?
Ex -  node dq_cli.js -src ['oie', 'xyz', 'abc']

**Comment by rajeshgrs** [comment]
No Jeevan. For now this should be sufficient. I'm keeping this as low
priority one.

**Comment by jeevanjagadeesh** [comment]
ok. Then shall i close this?

**Comment by rajeshgrs** [comment]
Keep it on hold for now. I have created new pull request. Please look into
it.

**Comment by jeevanjagadeesh** [comment]
Handled via - https://github.com/rajeshgrs/dq-cli/issues/28
