### ISSUE TITLE
readLogFile method in /lib/sendmail.js is not able to return the value to calling main method

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#10]
readLogFile method in /lib/sendmail.js is not able to return the value to calling main method.

**Comment by rajeshgrs** [comment]
Priority 1: https://github.com/rajeshgrs/dq-cli/issues/8
              https://github.com/rajeshgrs/dq-cli/issues/9

Priority 2: https://github.com/rajeshgrs/dq-cli/issues/11

Priority 3: https://github.com/rajeshgrs/dq-cli/issues/10

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh, I have modified the code to fix return code issue. Now need to find a way to merge this in main code dq_cli.js . Also not sure if we can change the gmail service to our Organization. Let me know if any inputs on this.

Attached zip file contains sendemail.js and dq_cli.log input file.

[sendmail.zip](https://github.com/rajeshgrs/dq-cli/files/710635/sendmail.zip)

**Comment by rajeshgrs** [comment]
May be this can be prioritized now.

**Comment by jeevanjagadeesh** [comment]
Replaced with emailjs modules, hence this bug is no longer valid.
