### ISSUE TITLE
Include Linux specific node executable to make current project folder compatible on Linux machine

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#12]
Include Linux specific node executable to make current project folder compatible on Linux machine

**Comment by jeevanjagadeesh** [comment]
Binaries are available at the below location.  Need to download the corresponding binary based on Processor (x86, x64)
https://nodejs.org/en/download/

**Comment by rajeshgrs** [comment]
Hi @jeevanjagadeesh , Please find attached image file on the concern I had. 
![node_linux](https://cloud.githubusercontent.com/assets/24637429/21804075/1b9fd034-d753-11e6-9ab4-229bff95507e.jpg)

**Comment by jeevanjagadeesh** [comment]
Fixed
