### ISSUE TITLE
Node Program for Validation of Log Files and Generating XML for Reporting

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#13]
Require Node Program for Validating Log Files and Generating XML for Reporting.
Please find attached zip file that contains sample log files, in
[LogValidation.zip](https://github.com/rajeshgrs/dq-cli/files/698064/LogValidation.zip)
put excel file, global properties file, success/failure pattern properties file, expected XML output. 
 There is one PPT "More_Info_On_XML_Attributes_And_Values_Expected_In_Output.pptx" that gives more information on what each attribute in xml is meant for.

  I am not sure of the approach of creating XML file. May be you capture all required data in some excel first and then finally convert that excel to XML? I wish it can be done this way, so that if XML creation fails or if XML got created incorrectly, then we can trace back what is causing the error by looking at data in excel. We may store this excel in folder called "TempFiles". 

Let me know if any questions/concerns.

@jeevanjagadeesh

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , you may work on top of current code or separately. But please bare in mind that we need to integrate it later with main code.

**Comment by jeevanjagadeesh** [comment]
<timeTaken>24</timeTaken> - log does not have time info, how to get this info?

From where do we get these info
<buildNumber>46</buildNumber>
    <branchName>ML</branchName>
    <productVersion>10.2.0</productVersion>
    <executionMode/>
    <operatingSystem/>
    <databaseType>ORACLE</databaseType>
    <databaseVersion/>
    <buildURL/>
    <moduleName>DQT</moduleName>

**Comment by rajeshgrs** [comment]
​@JeevanJagadeesh, As I mentioned in the comment description, we should
find some-way in main code to store this time information, so that it can
be used for reporting.

​Below information are available in

​
\LogValidation\properties
​\​
config
​.json​

46
ML
10.2.0
ORACLE
​D​
Q​

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , cant we log the execution time in the log file?

**Comment by jeevanjagadeesh** [comment]
https://github.com/rajeshgrs/dq-cli/pull/15

**Comment by rajeshgrs** [comment]
I just found a way to log execution time in log file.. Need to make
modification to template file and add "ptime" executable in node project.
Please find below information on how we can populate execute time in log
file.



###################################################################################################################
Windows
###################################################################################################################

C:\Users\rar\Downloads\ptime-10>ptime dir

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

===  dir ===
 Volume in drive C is Windows
 Volume Serial Number is F22B-8C84

 Directory of C:\Users\rar\Downloads\ptime-10

01/11/2017  03:22 PM    <DIR>          .
01/11/2017  03:22 PM    <DIR>          ..
09/21/2002  11:30 AM            24,576 ptime.exe
09/21/2002  11:30 AM             2,100 ptime.txt
               2 File(s)         26,676 bytes
               2 Dir(s)   6,793,576,448 bytes free

Execution time: 0.035 s

###################################################################################################################
Linux
###################################################################################################################

[dq90_qa@IRL64DQD04 bin]$ /usr/bin/time -f "Execution time: %e s" sleep 2
Execution time: 2.00 s

###################################################################################################################

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh ,

  I have attached new set of log files that captures execution time. The log information is same as the one I shared before, but it will have some additional lines and the last line will have the pattern as "Execution time: 2.00 s" from which we should extract the time value between "Execution time: " and " s" string patterns.

Please proceed with it as a baseline for framing the code to populate execution time for QATrack report XML.

Let me know if any queries.
File attached here.
[cli_testcaseid_logs.zip](https://github.com/rajeshgrs/dq-cli/files/701247/cli_testcaseid_logs.zip)

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , So I believe you have all the info to populate reporting XML.

**Comment by jeevanjagadeesh** [comment]
Closing this - https://github.com/rajeshgrs/dq-cli/pull/15
