### ISSUE TITLE
Appending redundant blank lines in the output file

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#2]
For a given input file, the output generates too many redundant blank lines. Need to remove  those lines.

Current output
---------------------------------------------------------------------------------------------------------------

infacmd oie exportObjects -dn Domain_116 -un Administrator -pd Administrator -sdn Native -rs MSR_DQ -pn CLU_PROJECT -fp "oie_mapping_export_1.xml" -ow true -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cp "oie_export_ctl_1.xml"

infacmd oie exportObjects -dn Domain_116 -un Administrator -pd Administrator -sdn Native -rs MSR_DQ -pn CLU_PROJECT -fp "oie_mapping_export_2.xml" -ow true -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cp "oie_export_ctl_2.xml"

infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp oie_mapping_export.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr replace

infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp run_dq_sanity.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr rename

infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp run_dq_sanity_2.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr rename

infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp oie_mapping_export_2.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr replace

-------------------------------------------------------------------------------------------------------------

#########################################################################
Expected output
-------------------------------------------------------------------------------------------------------------
There should be blank line for commands generated within a sheet. Blank line should be appended only between the sheets as shown below.

infacmd oie exportObjects -dn Domain_116 -un Administrator -pd Administrator -sdn Native -rs MSR_DQ -pn CLU_PROJECT -fp "oie_mapping_export_1.xml" -ow true -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cp "oie_export_ctl_1.xml"
infacmd oie exportObjects -dn Domain_116 -un Administrator -pd Administrator -sdn Native -rs MSR_DQ -pn CLU_PROJECT -fp "oie_mapping_export_2.xml" -ow true -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cp "oie_export_ctl_2.xml"

infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp oie_mapping_export.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr replace
infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp run_dq_sanity.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr rename
infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp run_dq_sanity_2.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr rename
infacmd oie importObjects -dn Domain_116 -un Administrator -pd Administrator -rs MSR_DQ -tp PAM -sp PAM_910 -fp oie_mapping_export_2.xml -oo "adapter:pluginCheck=false;rtm:codePage=UTF-8,refDataFile="/"" -cr replace

@jeevanjagadeesh , could you please take care of this.

**Comment by jeevanjagadeesh** [comment]
Guess, i fixed this :)
