### ISSUE TITLE
Parsing log files and storing command running status for each " TestCaseID" in a XML file.

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#9]
Once we are done with execution of all the cli commands:-
    a) Another child process should trigger to parse generated log files for each TestCaseID.
        Attached zip file contains some sample output log files for "oie" plugin and "CLI_errors.xlx" sheet in the zip file has some error patterns obtained from the log.  
    b) Status of "TestCaseID" parsed should be stored in an XML format. Sample XML format "QATrackerReport.xml" is attached. Our reporting tool expects the XML in this format only.

[parse_logs.zip](https://github.com/rajeshgrs/dq-cli/files/693269/parse_logs.zip)

[QATrackerReport.zip](https://github.com/rajeshgrs/dq-cli/files/693270/QATrackerReport.zip)

**Comment by rajeshgrs** [comment]
This is the XML file that will be used later at the end stage of process to call a java program that requires this xml file as one of the argument. I have already included a java program in the code. We just need to have a XML file for the java program to run.

**Comment by rajeshgrs** [comment]
Priority 1: https://github.com/rajeshgrs/dq-cli/issues/8
              https://github.com/rajeshgrs/dq-cli/issues/9

Priority 2: https://github.com/rajeshgrs/dq-cli/issues/11

Priority 3: https://github.com/rajeshgrs/dq-cli/issues/10

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , finding it difficult to find a common log pattern.
Is there a possibility to have some pattern or keywords to look for in the logs.
How is the current log to xml conversion done?

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh, not sure if you have downloaded this file https://github.com/rajeshgrs/dq-cli/files/693269/parse_logs.zip . It has CLI_errors.xlsx that has common patterns to find whether command has failed or not.

This is how it is:
 1) If there is a string pattern "ICMD_10033" in the log file, that will indicate execution has failed. Now the test status will be taken as "Fail" and we should fetch complete log to include it in "Comments" while reporting this test case.
Example: Comments should have below info.
ERROR(s):
Control file [C:\dq-cli\jan4\dq-cli\cli_results\output\oieexportsobjects_ctl.xml] does not exist.
[ICMD_10033] Command [exportObjects] failed with error [[OIECMD_10006] Error occurred during export function. See previous error.].


2)If the command run successfully, then log will have string pattern as "Command ran successfully".

Attached sample success & failure log file

[sample_logs.zip](https://github.com/rajeshgrs/dq-cli/files/695870/sample_logs.zip)




Let me know if this clarifies.

**Comment by jeevanjagadeesh** [comment]
Done
